# Generated by Django 6.0.3 on 2026-04-09 16:37

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_recipe_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(
                    django.db.models.functions.text.Trim("title")
                ),
                models.F("owner"),
                name="unique_recipe_title_per_owner_ci",
                violation_error_message="Már van ilyen nevű recepted.",
            ),
        ),
    ]
