# Generated by Django 6.0.3 on 2026-04-09 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_recipe_unique_recipe_title_per_owner_ci"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cooking_time__gte", 1), ("cooking_time__lte", 1440)
                ),
                name="recipe_cooking_time_between_1_and_1440",
                violation_error_message="A főzési idő 1 és 1440 perc között lehet.",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(("servings__gte", 1), ("servings__lte", 20)),
                name="recipe_servings_between_1_and_20",
                violation_error_message="Az adagok száma 1 és 20 között lehet.",
            ),
        ),
    ]
